name: Build aarch64-darwin binary

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build with Nix
        run: |
          nix build --print-build-logs --no-link --out-link -f result default.nix

      - name: List build outputs
        run: |
          echo "Build outputs:"
          ls -lh result
