name: Build aarch64-darwin binary

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build test binary for aarch64-darwin
        run: nix build .#hsPkgs --system aarch64-darwin

      - name: List result
        run: ls -l result
